### ISSUE TITLE
Appliance Key / Serial No in HA

### ISSUE THREAD

**Issue by klodeckel1990** [matthias1232/kpc_sophosxg#2]
Is it possible to implement Appliance Key for Standy-Appliance in HA?

**Comment by matthias1232** [comment]
![image](https://github.com/matthias1232/kpc_sophosxg/assets/5358267/776bd483-eeb8-4c54-9baa-4fdf0fb55568)

Should be possible, but im not sure to which check i should add this information.

Maybe additional to "Sophos Device Info"

**Comment by klodeckel1990** [comment]
Could you implement it? :) As Sophos Device Info would be totally fine!

**Comment by matthias1232** [comment]
I will try with the next Version to implement it. As soon i have my next Cluster Test environment ready i can try to add it.

**Comment by matthias1232** [comment]
https://github.com/matthias1232/kpc_sophosxg/releases/tag/1.0.3
